[scripts] Improve check_page

diff --git a/scripts/.local/bin/check_page b/scripts/.local/bin/check_page
--- a/scripts/.local/bin/check_page
+++ b/scripts/.local/bin/check_page
@@ -1,9 +1,13 @@
 #!/bin/sh
 # Check if an XPath selector produces results on a page.
+# If elements are found, append a notification to an improvized
+# "mailbox", which is just a plain text file in home directory.
+#
 # Exit code is 0 if search is successful, 1 otherwise.
 #
 # Dependencies:
 # - curl
+# - libnotify
 # - xmllint
 #
 # Example:
@@ -15,7 +19,15 @@ description="$3"
 
 echo "Checking '$xpath' at '$url'"
 
-(curl --silent "$url" |
+page="$(curl --silent --insecure "$url")"
+[ -z "$page" ] && echo "Error: couldn't get the page" && exit 1
+
+(echo "$page" |
     xmllint --html --xpath "$xpath" - >/dev/null 2>&1) &&
-    (echo "Found $description"; notify-send "Found elements at $url ($description)" ; exit 0) ||
-    (echo "Couldn't find $description"; exit 1)
+    (
+        notification="Found elements at $url ($description)"
+        echo "$notification" | tee --append "$HOME/mailbox"
+        notify-send "$notification"
+        exit 0
+    ) ||
+        (echo "Couldn't find $description"; exit 1)
