[scripts] Fix fzf_containers

diff --git a/scripts/.local/bin/fzf_containers b/scripts/.local/bin/fzf_containers
--- a/scripts/.local/bin/fzf_containers
+++ b/scripts/.local/bin/fzf_containers
@@ -3,17 +3,19 @@
 # .docker_aliases script is required.
 # Docker commands are different from the default here.
 
-. ~/.dotfiles/bash/.config/bash/docker_aliases
+command -v docker-alias-wrapper > /dev/null ||
+    echo 'docker-alias-wrapper script is required' &&
+    exit 1
 
 FZF_DEFAULT_OPTS="--reverse --height 40% $FZF_DEFAULT_OPTS"
 
-choice="$(docker ps |
+choice="$(docker-alias-wrapper ps |
     awk 'NR>1 {print $3}' |
     fzf)"
 
 [ -z "$choice" ] && exit 1
 
-docker ex "$choice"
+docker-alias-wrapper ex "$choice"
 
 # Add newline at the end.
 echo
